// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcnvVYtZoiyHtJo9mrrcAMamBUMUQXgpQ',
    appId: '1:560695154144:web:2ac90138e5039a395dc785',
    messagingSenderId: '560695154144',
    projectId: 'login-screen-10afc',
    authDomain: 'login-screen-10afc.firebaseapp.com',
    storageBucket: 'login-screen-10afc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWcnPjzweHInPwDXImnailhHnawi5cCgw',
    appId: '1:560695154144:android:06c764ed7b02b5c35dc785',
    messagingSenderId: '560695154144',
    projectId: 'login-screen-10afc',
    storageBucket: 'login-screen-10afc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl8H5p-H-mVvWMnqppubxCRedrPB5vORQ',
    appId: '1:560695154144:ios:facffb79b22706295dc785',
    messagingSenderId: '560695154144',
    projectId: 'login-screen-10afc',
    storageBucket: 'login-screen-10afc.appspot.com',
    iosClientId: '560695154144-l7k11e72kor2mhdhc8p3ki7ph1b3jrls.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginScreen',
  );
}
